In [1]:
# Dependencies
import json
import pandas as pd
import requests
from matplotlib import pyplot as plt 
from config import api_key

In [2]:
url = 'https://api.yelp.com/v3/businesses/search'
headers = {'Authorization': 'Bearer %s' % api_key}
params = {'location':'Oregon', 'offset':0, 'limit' : 50}
req=requests.get(url, params=params, headers=headers).json()

In [3]:

rest_list = []
for x in req['businesses'] :
    rest_list.append(x['name'])
rest_list

['Screen Door',
 'Salt & Straw',
 'Tasty n Alder',
 'Mother’s Bistro & Bar',
 "Pip's Original Doughnuts & Chai",
 'Pine State Biscuits',
 'Andina Restaurant',
 'Blue Star Donuts',
 'Salt & Straw',
 'Voodoo Doughnut - Old Town',
 'Pok Pok',
 'Salt & Straw',
 'Deschutes Brewery Portland Public House',
 'The Waffle Window',
 'Lúc Lác',
 'Toro Bravo',
 'Lechon',
 "Nong's Khao Man Gai",
 'Cheryl’s on 12th',
 'The Observatory',
 'Le Pigeon',
 'Portland City Grill',
 'Ovation Coffee & Tea',
 'Broder Café',
 'Pambiche',
 'Tin Shed',
 'International Rose Test Garden',
 'Grassa',
 'Pine State Biscuits',
 'Petite Provence',
 'PDX Sliders',
 'Tōv',
 'Blossoming Lotus',
 'Q Restaurant & Bar',
 'Apizza Scholls',
 'Portland Japanese Garden',
 'Jam On Hawthorne',
 'Olympia Provisions',
 'Lardo',
 'Mediterranean Exploration Company',
 'Sivalai Thai Restaurant',
 'Ox',
 'Ground Kontrol Classic Arcade',
 'Kachka',
 'Bamboo Sushi',
 'Lardo',
 'Nicholas Restaurant',
 'Cuon - Vietnamese Street Food',
 'Gravy',
 'Cacao Drink Chocolate']

In [53]:
rest_df = pd.DataFrame({'Name': rest_list, 'Review_Count': '' , 'Rating': '', 'Price': ''})
rest_df

                                       Name Review_Count Rating Price
0                               Screen Door
1                              Salt & Straw
2                             Tasty n Alder
3                     Mother’s Bistro & Bar
4           Pip's Original Doughnuts & Chai
5                       Pine State Biscuits
6                         Andina Restaurant
7                          Blue Star Donuts
8                              Salt & Straw
9                Voodoo Doughnut - Old Town
10                                  Pok Pok
11                             Salt & Straw
12  Deschutes Brewery Portland Public House
13                        The Waffle Window
14                                  Lúc Lác
15                               Toro Bravo
16                                   Lechon
17                      Nong's Khao Man Gai
18                         Cheryl’s on 12th
19                          The Observatory
20                                Le Pigeon
21                      Portland City Grill
22                     Ovation Coffee & Tea
23                              Broder Café
24                                 Pambiche
25                                 Tin Shed
26           International Rose Test Garden
27                                   Grassa
28                      Pine State Biscuits
29                          Petite Provence
30                              PDX Sliders
31                                      Tōv
32                         Blossoming Lotus
33                       Q Restaurant & Bar
34                           Apizza Scholls
35                 Portland Japanese Garden
36                         Jam On Hawthorne
37                       Olympia Provisions
38                                    Lardo
39                           Swiss Hibiscus
40        Mediterranean Exploration Company
41                  Sivalai Thai Restaurant
42                                       Ox
43            Ground Kontrol Classic Arcade
44                             Bamboo Sushi
45                                   Kachka
46                                    Lardo
47                      Nicholas Restaurant
48            Cuon - Vietnamese Street Food
49                                    Gravy

In [8]:
inspection_df = pd.read_csv('CSV_1_29_20.csv')
inspection_df

,Name,Score,Address,City,Zip
0,McCormick and Schmicks Harborside at the Marina,93.250000,0309 SW Montgomery St,Portland,97201.0
1,Yomi Sushi,97.333333,0315 SW Montgomery St 120,Portland,97201.0
2,Upstream Coffee,95.000000,0315 SW Montgomery St 200,Portland,97201.0
3,Little River Cafe,100.000000,0315 SW Montgomery St 310,Portland,97201.0
4,IL Terrazzo,91.000000,0315 SW Montgomery St Suite 340,Portland,97201.0
...,...,...,...,...,...
3164,Aloft Portland Airport at Cascade Station,97.750000,9920 NE Cascades Pkwy,Portland,97220.0
3165,Parkstone Wood Kitchen,93.333333,9921 NE Cascades Pkwy,Portland,97220.0
3166,Country Inn & Suites by Carlson,99.250000,9930 N Whitaker Rd,Portland,97217.0
3167,Club 205 Tavern,95.666667,9939 SE Stark St,Portland,97216.0
3168,The Venue - Falcos,100.000000,9950 SE Stark St,Portland,97216.0

In [10]:
inspection_df['Rating'] = ''
inspection_df['Review Count'] = ''
inspection_df['Price'] = ''
inspection_df

,Name,Score,Address,City,Zip,Rating,Review Count,Price
0,McCormick and Schmicks Harborside at the Marina,93.250000,0309 SW Montgomery St,Portland,97201.0,,,
1,Yomi Sushi,97.333333,0315 SW Montgomery St 120,Portland,97201.0,,,
2,Upstream Coffee,95.000000,0315 SW Montgomery St 200,Portland,97201.0,,,
3,Little River Cafe,100.000000,0315 SW Montgomery St 310,Portland,97201.0,,,
4,IL Terrazzo,91.000000,0315 SW Montgomery St Suite 340,Portland,97201.0,,,
...,...,...,...,...,...,...,...,...
3164,Aloft Portland Airport at Cascade Station,97.750000,9920 NE Cascades Pkwy,Portland,97220.0,,,
3165,Parkstone Wood Kitchen,93.333333,9921 NE Cascades Pkwy,Portland,97220.0,,,
3166,Country Inn & Suites by Carlson,99.250000,9930 N Whitaker Rd,Portland,97217.0,,,
3167,Club 205 Tavern,95.666667,9939 SE Stark St,Portland,97216.0,,,
3168,The Venue - Falcos,100.000000,9950 SE Stark St,Portland,97216.0,,,

In [ ]:
url = 'https://api.yelp.com/v3/businesses/search'
headers = {'Authorization': 'Bearer %s' % api_key}
params = {'location':'Oregon', 'limit' : 50}

params['offset'] = 0
for index, row in inspection_df.iterrows():
    req=requests.get(url, params=params, headers=headers).json()
    
    for:
        rest_df.loc[index, "Review_Count"] = req["businesses"][0]["review_count"]
        #rest_df.loc[index, "Categories"] = req["businesses"][0]["categories"]
        rest_df.loc[index, "Rating"] = req["businesses"][0]["rating"]
        rest_df.loc[index, "Price"] = req["businesses"][0]["price"]
        params['offset'] +=50
    
rest_df

,Name,Score,Address,City,Zip
0,McCormick and Schmicks Harborside at the Marina,93.250000,0309 SW Montgomery St,Portland,97201.0
1,Yomi Sushi,97.333333,0315 SW Montgomery St 120,Portland,97201.0
2,Upstream Coffee,95.000000,0315 SW Montgomery St 200,Portland,97201.0
3,Little River Cafe,100.000000,0315 SW Montgomery St 310,Portland,97201.0
4,IL Terrazzo,91.000000,0315 SW Montgomery St Suite 340,Portland,97201.0
...,...,...,...,...,...
3164,Aloft Portland Airport at Cascade Station,97.750000,9920 NE Cascades Pkwy,Portland,97220.0
3165,Parkstone Wood Kitchen,93.333333,9921 NE Cascades Pkwy,Portland,97220.0
3166,Country Inn & Suites by Carlson,99.250000,9930 N Whitaker Rd,Portland,97217.0
3167,Club 205 Tavern,95.666667,9939 SE Stark St,Portland,97216.0
3168,The Venue - Falcos,100.000000,9950 SE Stark St,Portland,97216.0